import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingVertical: 35,
    backgroundColor: "rgba(0,0,0,0.48)",
  },
  modalCard: {
    width: "100%",
    maxHeight: "92%",
    padding: 20,
    alignSelf: "center",
    borderRadius: 24,
    backgroundColor: "#ffffff",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.22,
    shadowRadius: 22,
    elevation: 14,
  },
  iconContainer: {
    width: 70,
    height: 70,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 35,
    backgroundColor: "#e9f8ef",
  },
  title: {
    marginTop: 15,
    color: "#20242a",
    fontSize: 22,
    fontWeight: "900",
    textAlign: "center",
  },
  description: {
    marginTop: 8,
    color: "#747b84",
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
  summaryCard: {
    marginTop: 20,
    paddingHorizontal: 15,
    borderRadius: 16,
    backgroundColor: "#f7f8fa",
  },
  summaryRow: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#e9ebee",
  },
  lastSummaryRow: {
    borderBottomWidth: 0,
  },
  summaryLabel: {
    color: "#747b84",
    fontSize: 12,
    fontWeight: "600",
  },
  summaryValue: {
    flexShrink: 1,
    color: "#30363d",
    fontSize: 13,
    fontWeight: "800",
    textAlign: "right",
  },
  total: {
    color: "#c8231b",
    fontSize: 15,
    fontWeight: "900",
  },
  productsSection: {
    marginTop: 18,
  },
  productsTitle: {
    marginBottom: 4,
    color: "#40464d",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  productRow: {
    minHeight: 51,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#eeeeee",
  },
  productName: {
    color: "#353b42",
    fontSize: 13,
    fontWeight: "700",
  },
  productPrice: {
    marginTop: 3,
    color: "#8b9198",
    fontSize: 11,
  },
  productQuantity: {
    color: "#c8231b",
    fontSize: 13,
    fontWeight: "900",
  },
  questionBox: {
    marginTop: 20,
    padding: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    borderWidth: 1,
    borderColor: "#f4cdca",
    borderRadius: 14,
    backgroundColor: "#fff7f6",
  },
  questionText: {
    flex: 1,
    color: "#5a4240",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
  },
  confirmButton: {
    height: 53,
    marginTop: 17,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 14,
    backgroundColor: "#c8231b",
  },
  confirmButtonText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "900",
  },
  notReceivedButton: {
    height: 48,
    marginTop: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#e6b8b5",
    borderRadius: 14,
    backgroundColor: "#ffffff",
  },
  notReceivedText: {
    color: "#b42318",
    fontSize: 12,
    fontWeight: "800",
  },
  laterButton: {
    minHeight: 42,
    marginTop: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  laterText: {
    color: "#8b9198",
    fontSize: 12,
    fontWeight: "700",
  },
  rejectContainer: {
    marginTop: 15,
  },
  rejectAlertBox: {
    padding: 14,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    borderWidth: 1,
    borderColor: "#fecaca",
    borderRadius: 14,
    backgroundColor: "#fef2f2",
    marginBottom: 16,
  },
  rejectAlertText: {
    flex: 1,
    color: "#991b1b",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
  },
  rejectInputLabel: {
    fontSize: 13,
    fontWeight: "800",
    color: "#374151",
    marginBottom: 6,
  },
  rejectInput: {
    minHeight: 95,
    borderWidth: 1.5,
    borderColor: "#d1d5db",
    borderRadius: 14,
    padding: 12,
    fontSize: 14,
    color: "#1f2937",
    backgroundColor: "#f9fafb",
    textAlignVertical: "top",
  },
  rejectInputError: {
    borderColor: "#ef4444",
    backgroundColor: "#fff5f5",
  },
  rejectErrorText: {
    marginTop: 5,
    color: "#dc2626",
    fontSize: 12,
    fontWeight: "700",
  },
  submitRejectButton: {
    height: 52,
    marginTop: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 14,
    backgroundColor: "#dc2626",
  },
  submitRejectButtonText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
  },
  backButton: {
    height: 46,
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 14,
    backgroundColor: "#ffffff",
  },
  backButtonText: {
    color: "#4b5563",
    fontSize: 13,
    fontWeight: "700",
  },
});
