import { StyleSheet } from "react-native";

export const ROJO = "#c8231b";
export const ROJO_OSCURO = "#971711";
export const ROJO_CLARO = "#fff0ef";
export const GRIS_FONDO = "#f5f6f8";
export const BLANCO = "#ffffff";
export const TEXTO_PRINCIPAL = "#20242a";
export const TEXTO_SECUNDARIO = "#707780";
export const BORDE_TARJETA = "#eceef1";

export const styles = StyleSheet.create({
  pantalla: {
    flex: 1,
    backgroundColor: GRIS_FONDO,
  },
  safeArea: {
    flex: 1,
    backgroundColor: GRIS_FONDO,
  },
  contenido: {
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 110,
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: GRIS_FONDO,
  },
  loadingText: {
    marginTop: 12,
    color: TEXTO_SECUNDARIO,
    fontSize: 14,
    fontWeight: "600",
  },

  // Encabezado
  encabezado: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 18,
    marginTop: 4,
  },
  titulo: {
    color: TEXTO_PRINCIPAL,
    fontSize: 26,
    fontWeight: "900",
    letterSpacing: -0.3,
  },
  subtitulo: {
    marginTop: 3,
    color: TEXTO_SECUNDARIO,
    fontSize: 13,
  },
  btnNuevoPedido: {
    backgroundColor: ROJO,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    shadowColor: ROJO,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 3,
  },
  btnNuevoPedidoTexto: {
    color: BLANCO,
    fontSize: 12,
    fontWeight: "800",
  },

  // Hero Banner
  heroBanner: {
    backgroundColor: ROJO,
    borderRadius: 22,
    padding: 20,
    marginBottom: 18,
    shadowColor: ROJO_OSCURO,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 5,
    position: "relative",
    overflow: "hidden",
  },
  heroDecorCircle1: {
    position: "absolute",
    top: -60,
    right: -40,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: "rgba(255, 255, 255, 0.09)",
  },
  heroDecorCircle2: {
    position: "absolute",
    bottom: -60,
    left: -40,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: "rgba(0, 0, 0, 0.07)",
  },
  heroHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  heroIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "rgba(255, 255, 255, 0.18)",
    alignItems: "center",
    justifyContent: "center",
  },
  heroTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: BLANCO,
  },
  heroSubtitle: {
    fontSize: 12,
    color: "rgba(255, 255, 255, 0.85)",
    marginTop: 2,
  },
  statsContainer: {
    flexDirection: "row",
    gap: 10,
    marginTop: 14,
  },
  statsScroll: {
    marginTop: 14,
    marginHorizontal: -4,
  },
  statsScrollContainer: {
    paddingHorizontal: 4,
    gap: 8,
  },
  statCardHero: {
    minWidth: 105,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.25)",
    justifyContent: "center",
  },
  statCardHeroActive: {
    backgroundColor: "rgba(255, 255, 255, 0.32)",
    borderColor: "#ffffff",
  },
  statCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  statCardValue: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "900",
  },
  statCardLabel: {
    color: "rgba(255, 255, 255, 0.9)",
    fontSize: 11,
    fontWeight: "700",
    marginTop: 3,
  },
  statBox: {
    flex: 1,
    backgroundColor: ROJO_CLARO,
    borderRadius: 16,
    padding: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#f5d0cd",
  },
  statValue: {
    color: ROJO,
    fontSize: 20,
    fontWeight: "900",
  },
  statLabel: {
    color: TEXTO_SECUNDARIO,
    fontSize: 11,
    fontWeight: "700",
    marginTop: 3,
    textAlign: "center",
  },

  // Buscador y Filtros
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: BLANCO,
    borderRadius: 16,
    paddingHorizontal: 14,
    height: 50,
    borderWidth: 1,
    borderColor: BORDE_TARJETA,
    marginBottom: 14,
    gap: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: TEXTO_PRINCIPAL,
  },
  filterScroll: {
    marginBottom: 14,
  },
  filterContainer: {
    flexDirection: "row",
    gap: 8,
    paddingBottom: 2,
  },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: BLANCO,
    borderWidth: 1,
    borderColor: BORDE_TARJETA,
  },
  filterChipActive: {
    backgroundColor: ROJO,
    borderColor: ROJO,
  },
  filterChipText: {
    fontSize: 12,
    fontWeight: "700",
    color: TEXTO_SECUNDARIO,
  },
  filterChipTextActive: {
    color: BLANCO,
  },

  // Tarjeta de Pedido
  tarjetaPedido: {
    backgroundColor: BLANCO,
    borderRadius: 20,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: BORDE_TARJETA,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  pedidoEncabezado: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  pedidoNumero: {
    fontSize: 16,
    fontWeight: "800",
    color: TEXTO_PRINCIPAL,
  },
  pedidoFecha: {
    fontSize: 11,
    color: "#9aa0a6",
    marginTop: 3,
    fontWeight: "500",
  },
  estadoBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
  },
  estadoBadgeTexto: {
    fontSize: 11,
    fontWeight: "800",
  },

  // Filas de info
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 10,
  },
  infoIconBox: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: ROJO_CLARO,
    alignItems: "center",
    justifyContent: "center",
  },
  infoContent: {
    flex: 1,
  },
  infoLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: "#9aa0a6",
    textTransform: "uppercase",
  },
  infoText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#343940",
    marginTop: 1,
  },

  // Desglose de montos
  resumenMontos: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#f8f9fb",
    borderRadius: 14,
    padding: 12,
    marginTop: 12,
    borderWidth: 1,
    borderColor: "#edf0f3",
  },
  montoEtiqueta: {
    fontSize: 10,
    fontWeight: "700",
    color: "#8a9098",
    textTransform: "uppercase",
  },
  montoTotal: {
    fontSize: 16,
    fontWeight: "900",
    color: ROJO,
    marginTop: 2,
  },
  montoPendiente: {
    fontSize: 13,
    fontWeight: "800",
    color: "#b42318",
  },
  montoPagado: {
    fontSize: 13,
    fontWeight: "800",
    color: "#15803d",
  },

  // Acciones
  acciones: {
    flexDirection: "row",
    gap: 8,
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#f3f4f6",
  },
  botonAccion: {
    flex: 1,
    minHeight: 42,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: 10,
  },
  botonDetalle: {
    backgroundColor: ROJO_CLARO,
    borderWidth: 1,
    borderColor: "#f2c4c1",
  },
  botonEditar: {
    backgroundColor: "#eff6ff",
    borderWidth: 1,
    borderColor: "#bfdbfe",
  },
  botonCancelar: {
    backgroundColor: "#fff1f2",
    borderWidth: 1,
    borderColor: "#fecaca",
  },
  botonAccionTexto: {
    fontSize: 12,
    fontWeight: "800",
  },

  // Estados vacíos
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 45,
    paddingHorizontal: 20,
    backgroundColor: BLANCO,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: BORDE_TARJETA,
    marginTop: 10,
  },
  emptyIconBox: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: ROJO_CLARO,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: TEXTO_PRINCIPAL,
    textAlign: "center",
  },
  emptyDescription: {
    color: TEXTO_SECUNDARIO,
    fontSize: 13,
    textAlign: "center",
    marginTop: 6,
    lineHeight: 18,
  },

  // Modal
  modalBg: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContainer: {
    backgroundColor: BLANCO,
    maxHeight: "88%",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 32,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 10,
  },
  modalHandle: {
    width: 42,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#d5d8dc",
    alignSelf: "center",
    marginBottom: 14,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f2f5",
    marginBottom: 14,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: TEXTO_PRINCIPAL,
  },
  modalCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#f2f4f7",
    alignItems: "center",
    justifyContent: "center",
  },
  modalSection: {
    backgroundColor: "#f9fafb",
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: BORDE_TARJETA,
  },
  modalSectionTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: TEXTO_SECUNDARIO,
    textTransform: "uppercase",
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  modalItemRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 5,
  },
  modalItemLabel: {
    fontSize: 13,
    color: TEXTO_SECUNDARIO,
    fontWeight: "600",
  },
  modalItemValue: {
    fontSize: 13,
    color: TEXTO_PRINCIPAL,
    fontWeight: "800",
  },

  productRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#edeef1",
  },
  productImageContainer: {
    width: 44,
    height: 44,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "#f5f6f8",
    marginRight: 10,
    borderWidth: 1,
    borderColor: "#eceef1",
    alignItems: "center",
    justifyContent: "center",
  },
  productImage: {
    width: "100%",
    height: "100%",
  },
  productIconSmall: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: ROJO_CLARO,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  productName: {
    fontSize: 14,
    fontWeight: "700",
    color: TEXTO_PRINCIPAL,
  },
  productUnitPrice: {
    marginTop: 2,
    color: TEXTO_SECUNDARIO,
    fontSize: 11,
  },
  productQtyBadge: {
    backgroundColor: ROJO_CLARO,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    marginBottom: 2,
  },
  productQtyText: {
    fontSize: 11,
    fontWeight: "800",
    color: ROJO,
  },
  productSubtotal: {
    fontSize: 14,
    fontWeight: "800",
    color: TEXTO_PRINCIPAL,
  },
  totalContainer: {
    backgroundColor: ROJO_CLARO,
    borderRadius: 16,
    padding: 16,
    marginTop: 10,
    marginBottom: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#f5cbca",
  },
  totalLabel: {
    fontSize: 15,
    fontWeight: "800",
    color: ROJO_OSCURO,
  },
  totalValue: {
    fontSize: 22,
    fontWeight: "900",
    color: ROJO,
  },

  // Controles de edición de cantidad
  counterContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f2f4f7",
    borderRadius: 12,
    padding: 3,
  },
  counterButton: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: BLANCO,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  counterValue: {
    paddingHorizontal: 12,
    fontSize: 14,
    fontWeight: "800",
    color: TEXTO_PRINCIPAL,
  },

  // Aviso en tarjeta de pedido
  cardAvisoEdicion: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#fffbeb",
    borderWidth: 1,
    borderColor: "#fde68a",
    borderRadius: 10,
    paddingVertical: 7,
    paddingHorizontal: 10,
    marginTop: 8,
  },
  cardAvisoEdicionTexto: {
    flex: 1,
    fontSize: 11,
    fontWeight: "700",
    color: "#b45309",
  },

  // Banner dentro del modal de detalle
  bannerMotivoEdicionCliente: {
    backgroundColor: "#fffbeb",
    borderWidth: 1,
    borderColor: "#fde68a",
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
  },
  bannerMotivoEdicionHeaderCliente: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  bannerMotivoEdicionTituloCliente: {
    fontSize: 13,
    fontWeight: "800",
    color: "#b45309",
  },
  bannerMotivoEdicionTextoCliente: {
    fontSize: 13,
    color: "#92400e",
    lineHeight: 18,
    fontWeight: "600",
  },

  // Modal Pop-up de Notificación de Edición
  modalNotificacionBg: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  modalNotificacionContainer: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: BLANCO,
    borderRadius: 24,
    padding: 22,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 18,
    elevation: 12,
  },
  modalNotificacionIconoBox: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#fef3c7",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  modalNotificacionTitulo: {
    fontSize: 19,
    fontWeight: "900",
    color: TEXTO_PRINCIPAL,
    textAlign: "center",
  },
  modalNotificacionSubtitulo: {
    fontSize: 13,
    color: TEXTO_SECUNDARIO,
    textAlign: "center",
    marginTop: 4,
    marginBottom: 16,
  },
  modalNotificacionCajaMotivo: {
    width: "100%",
    backgroundColor: "#fffbeb",
    borderWidth: 1.5,
    borderColor: "#fde68a",
    borderRadius: 14,
    padding: 14,
    marginBottom: 16,
  },
  modalNotificacionMotivoLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: "#b45309",
    textTransform: "uppercase",
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  modalNotificacionMotivoTexto: {
    fontSize: 14,
    fontWeight: "700",
    color: "#78350f",
    lineHeight: 20,
  },
  modalNotificacionTotalRow: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: "#f0f2f5",
    marginBottom: 18,
  },
  modalNotificacionTotalLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: TEXTO_SECUNDARIO,
  },
  modalNotificacionTotalValor: {
    fontSize: 17,
    fontWeight: "900",
    color: ROJO,
  },
  modalNotificacionBtnPrincipal: {
    width: "100%",
    minHeight: 48,
    borderRadius: 14,
    backgroundColor: ROJO,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    marginBottom: 10,
  },
  modalNotificacionBtnPrincipalTexto: {
    color: BLANCO,
    fontSize: 14,
    fontWeight: "800",
  },
  modalNotificacionBtnSecundario: {
    width: "100%",
    minHeight: 42,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  modalNotificacionBtnSecundarioTexto: {
    color: TEXTO_SECUNDARIO,
    fontSize: 13,
    fontWeight: "700",
  },
});
