import { StyleSheet } from "react-native";

export const ROJO = "#c8231b";
export const ROJO_OSCURO = "#971711";
export const ROJO_CLARO = "#fff0ef";
export const ROJO_SUAVE = "#fbe9e9";
export const GRIS_FONDO = "#f5f6f8";
export const BLANCO = "#ffffff";
export const TEXTO_PRINCIPAL = "#20242a";
export const TEXTO_SECUNDARIO = "#707780";
export const BORDE_TARJETA = "#eceef1";

export const styles = StyleSheet.create({
  // Pantalla y estructura base
  screen: {
    flex: 1,
    backgroundColor: GRIS_FONDO,
  },
  safeArea: {
    flex: 1,
    backgroundColor: GRIS_FONDO,
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 110,
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: GRIS_FONDO,
  },
  loadingText: {
    marginTop: 12,
    color: TEXTO_SECUNDARIO,
    fontSize: 14,
    fontWeight: "500",
  },

  // Encabezado superior tipo Cliente
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
    marginTop: 4,
  },
  greeting: {
    color: TEXTO_SECUNDARIO,
    fontSize: 13,
    fontWeight: "500",
    marginBottom: 3,
  },
  userName: {
    color: TEXTO_PRINCIPAL,
    fontSize: 24,
    fontWeight: "800",
    letterSpacing: -0.3,
  },
  avatarButton: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: ROJO_CLARO,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#f0c4c1",
  },
  avatarButtonActive: {
    backgroundColor: "#ffe8e6",
    borderColor: ROJO,
  },

  // Tarjeta Hero / Principal
  heroCard: {
    backgroundColor: BLANCO,
    borderRadius: 22,
    padding: 18,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: BORDE_TARJETA,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  heroBanner: {
    backgroundColor: ROJO,
    borderRadius: 22,
    padding: 20,
    marginBottom: 18,
    shadowColor: ROJO_OSCURO,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 5,
    position: "relative",
    overflow: "hidden",
  },
  heroDecorCircle1: {
    position: "absolute",
    top: -60,
    right: -40,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: "rgba(255, 255, 255, 0.09)",
  },
  heroDecorCircle2: {
    position: "absolute",
    bottom: -60,
    left: -40,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: "rgba(0, 0, 0, 0.07)",
  },
  heroHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  heroIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "rgba(255, 255, 255, 0.18)",
    alignItems: "center",
    justifyContent: "center",
  },
  heroTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: BLANCO,
  },
  heroSubtitle: {
    fontSize: 12,
    color: "rgba(255, 255, 255, 0.85)",
    marginTop: 2,
  },
  heroText: {
    marginTop: 10,
    color: "rgba(255, 255, 255, 0.9)",
    fontSize: 13,
    lineHeight: 19,
  },

  // Estadísticas y métricas
  statsContainer: {
    flexDirection: "row",
    gap: 10,
    marginTop: 14,
  },
  statBox: {
    flex: 1,
    backgroundColor: ROJO_CLARO,
    borderRadius: 16,
    padding: 13,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#f5d0cd",
  },
  statValue: {
    color: ROJO,
    fontSize: 22,
    fontWeight: "900",
  },
  statLabel: {
    color: TEXTO_SECUNDARIO,
    fontSize: 11,
    fontWeight: "700",
    marginTop: 3,
    textAlign: "center",
  },

  // Secciones y títulos
  sectionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 10,
    marginBottom: 13,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: TEXTO_PRINCIPAL,
    letterSpacing: -0.2,
  },
  badgeCount: {
    backgroundColor: ROJO_CLARO,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
  },
  badgeCountText: {
    color: ROJO,
    fontSize: 12,
    fontWeight: "800",
  },

  // Filtros horizontales
  filterScroll: {
    marginBottom: 14,
  },
  filterContainer: {
    flexDirection: "row",
    gap: 8,
    paddingBottom: 2,
  },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: BLANCO,
    borderWidth: 1,
    borderColor: BORDE_TARJETA,
  },
  filterChipActive: {
    backgroundColor: ROJO,
    borderColor: ROJO,
  },
  filterChipText: {
    fontSize: 12,
    fontWeight: "700",
    color: TEXTO_SECUNDARIO,
  },
  filterChipTextActive: {
    color: BLANCO,
  },

  // Tarjetas de pedidos
  card: {
    backgroundColor: BLANCO,
    borderRadius: 20,
    padding: 16,
    marginBottom: 13,
    borderWidth: 1,
    borderColor: BORDE_TARJETA,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  cardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  orderNumber: {
    fontSize: 16,
    fontWeight: "800",
    color: TEXTO_PRINCIPAL,
  },
  orderDate: {
    fontSize: 11,
    color: "#9aa0a6",
    marginTop: 3,
    fontWeight: "500",
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: "800",
  },

  // Filas de información en tarjeta
  cardBody: {
    marginTop: 10,
    gap: 8,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  infoIconBox: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: ROJO_CLARO,
    alignItems: "center",
    justifyContent: "center",
  },
  infoContent: {
    flex: 1,
  },
  infoLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: "#9aa0a6",
    textTransform: "uppercase",
  },
  infoText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#343940",
    marginTop: 1,
  },

  // Botones de acción en tarjetas
  cardActions: {
    flexDirection: "row",
    gap: 8,
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#f3f4f6",
  },
  btn: {
    flex: 1,
    minHeight: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: 12,
  },
  btnPrimary: {
    backgroundColor: ROJO,
  },
  btnPrimaryText: {
    color: BLANCO,
    fontWeight: "800",
    fontSize: 13,
  },
  btnSoft: {
    backgroundColor: ROJO_CLARO,
    borderWidth: 1,
    borderColor: "#f2c4c1",
  },
  btnSoftText: {
    color: ROJO,
    fontWeight: "800",
    fontSize: 13,
  },
  btnMap: {
    backgroundColor: "#eef7ff",
    borderWidth: 1,
    borderColor: "#cce5ff",
  },
  btnMapText: {
    color: "#1565c0",
    fontWeight: "800",
    fontSize: 13,
  },

  // Estados vacíos y errores
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 45,
    paddingHorizontal: 20,
    backgroundColor: BLANCO,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: BORDE_TARJETA,
    marginTop: 10,
  },
  emptyIconBox: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: ROJO_CLARO,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: TEXTO_PRINCIPAL,
    textAlign: "center",
  },
  emptyDescription: {
    color: TEXTO_SECUNDARIO,
    fontSize: 13,
    textAlign: "center",
    marginTop: 6,
    lineHeight: 18,
  },
  errorBanner: {
    marginVertical: 10,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "#ffeded",
    borderWidth: 1,
    borderColor: "#f8c8c5",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  errorText: {
    color: "#b42318",
    fontSize: 13,
    fontWeight: "600",
    flex: 1,
  },

  // Modal rediseñado
  modalBg: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContainer: {
    backgroundColor: BLANCO,
    maxHeight: "88%",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 32,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 10,
  },
  modalHandle: {
    width: 42,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#d5d8dc",
    alignSelf: "center",
    marginBottom: 14,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f2f5",
    marginBottom: 14,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: TEXTO_PRINCIPAL,
  },
  modalCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#f2f4f7",
    alignItems: "center",
    justifyContent: "center",
  },
  modalSection: {
    backgroundColor: "#f9fafb",
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: BORDE_TARJETA,
  },
  modalSectionTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: TEXTO_SECUNDARIO,
    textTransform: "uppercase",
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  modalItemRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 5,
  },
  modalItemLabel: {
    fontSize: 13,
    color: TEXTO_SECUNDARIO,
    fontWeight: "600",
  },
  modalItemValue: {
    fontSize: 13,
    color: TEXTO_PRINCIPAL,
    fontWeight: "800",
  },

  // Lista de productos en modal
  productRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#edeef1",
  },
  productName: {
    fontSize: 14,
    fontWeight: "700",
    color: TEXTO_PRINCIPAL,
  },
  productUnitPrice: {
    marginTop: 2,
    color: TEXTO_SECUNDARIO,
    fontSize: 11,
  },
  productQtyBadge: {
    backgroundColor: ROJO_CLARO,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    marginBottom: 2,
  },
  productQtyText: {
    fontSize: 11,
    fontWeight: "800",
    color: ROJO,
  },
  productSubtotal: {
    fontSize: 14,
    fontWeight: "800",
    color: TEXTO_PRINCIPAL,
  },
  totalContainer: {
    backgroundColor: ROJO_CLARO,
    borderRadius: 16,
    padding: 16,
    marginTop: 10,
    marginBottom: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#f5cbca",
  },
  totalLabel: {
    fontSize: 15,
    fontWeight: "800",
    color: ROJO_OSCURO,
  },
  totalValue: {
    fontSize: 22,
    fontWeight: "900",
    color: ROJO,
  },

  // Perfil estilos (Idénticos al Cliente)
  perfilHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 22,
  },
  perfilTitulo: {
    fontSize: 27,
    fontWeight: "800",
    color: "#202020",
    letterSpacing: -0.4,
  },
  perfilSubtitulo: {
    marginTop: 3,
    fontSize: 14,
    color: "#777",
  },
  botonEditar: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: ROJO,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: ROJO,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  avatarContainer: {
    alignItems: "center",
    marginBottom: 22,
  },
  avatar: {
    width: 94,
    height: 94,
    borderRadius: 47,
    backgroundColor: ROJO_SUAVE,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: BLANCO,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  nombrePrincipal: {
    marginTop: 12,
    fontSize: 21,
    fontWeight: "800",
    color: "#242424",
    letterSpacing: -0.2,
  },
  badgeEstadoRolRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
  },
  estado: {
    paddingHorizontal: 13,
    paddingVertical: 5,
    borderRadius: 20,
  },
  estadoActivo: {
    backgroundColor: "#DDF5E5",
  },
  estadoInactivo: {
    backgroundColor: "#F8DADA",
  },
  estadoTexto: {
    fontSize: 12,
    fontWeight: "700",
    color: "#3F3F3F",
  },
  rolBadge: {
    backgroundColor: ROJO_CLARO,
    paddingHorizontal: 13,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#f5d0cd",
  },
  rolBadgeTexto: {
    fontSize: 12,
    fontWeight: "800",
    color: ROJO,
  },

  // Tarjeta de Formulario
  tarjeta: {
    backgroundColor: BLANCO,
    borderRadius: 20,
    padding: 18,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: BORDE_TARJETA,
  },
  campoContainer: {
    marginBottom: 17,
  },
  etiqueta: {
    marginBottom: 7,
    fontSize: 13,
    fontWeight: "700",
    color: "#484848",
  },
  inputContainer: {
    minHeight: 53,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E2E2E2",
    backgroundColor: "#FAFAFA",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  inputDeshabilitado: {
    backgroundColor: "#EEEEEE",
    borderColor: "#E5E5E5",
  },
  input: {
    flex: 1,
    fontSize: 15,
    color: "#272727",
  },
  correoAviso: {
    marginTop: -7,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  correoAvisoTexto: {
    flex: 1,
    fontSize: 12,
    color: "#777",
  },
  seccionTituloContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  seccionTitulo: {
    fontSize: 17,
    fontWeight: "800",
    color: "#282828",
  },
  seccionDescripcion: {
    marginTop: 5,
    marginBottom: 17,
    fontSize: 13,
    color: "#777",
  },
  acciones: {
    flexDirection: "row",
    gap: 12,
    marginTop: 4,
    marginBottom: 16,
  },
  botonCancelar: {
    flex: 1,
    minHeight: 53,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#D4D4D4",
    backgroundColor: BLANCO,
    alignItems: "center",
    justifyContent: "center",
  },
  botonCancelarTexto: {
    color: "#555",
    fontSize: 15,
    fontWeight: "700",
  },
  botonGuardar: {
    flex: 2,
    minHeight: 53,
    borderRadius: 15,
    backgroundColor: ROJO,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    shadowColor: ROJO,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  botonGuardarTexto: {
    color: BLANCO,
    fontSize: 15,
    fontWeight: "800",
  },
  botonDeshabilitado: {
    opacity: 0.65,
  },
  botonCerrarSesion: {
    minHeight: 52,
    borderRadius: 15,
    backgroundColor: "#ffeded",
    borderWidth: 1,
    borderColor: "#f8c8c5",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 8,
  },
  botonCerrarSesionTexto: {
    color: "#b42318",
    fontSize: 15,
    fontWeight: "800",
  },

  // Pagos y Cobros estilos
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: BLANCO,
    borderRadius: 16,
    paddingHorizontal: 14,
    height: 50,
    borderWidth: 1,
    borderColor: BORDE_TARJETA,
    marginBottom: 14,
    gap: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: TEXTO_PRINCIPAL,
  },
  btnRegistrarPago: {
    backgroundColor: ROJO,
    borderRadius: 16,
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginBottom: 16,
    shadowColor: ROJO,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 3,
  },
  btnRegistrarPagoTexto: {
    color: BLANCO,
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  paymentCard: {
    backgroundColor: BLANCO,
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: BORDE_TARJETA,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  paymentCardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  paymentAmount: {
    fontSize: 18,
    fontWeight: "900",
    color: "#1e874b",
  },
  paymentMethodBadge: {
    backgroundColor: ROJO_CLARO,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  paymentMethodText: {
    fontSize: 11,
    fontWeight: "700",
    color: ROJO,
  },
  paymentMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
  },
  paymentMetaText: {
    fontSize: 12,
    color: TEXTO_SECUNDARIO,
  },
  paymentBalanceRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#f3f4f6",
  },
  balancePaidBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  balancePaidText: {
    color: "#1e874b",
    fontSize: 12,
    fontWeight: "700",
  },
  balancePendingText: {
    color: ROJO,
    fontSize: 12,
    fontWeight: "700",
  },

  // Selector chips en modal de pago
  selectorWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
    marginBottom: 14,
  },
  chipItem: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "#f4f5f7",
    borderWidth: 1,
    borderColor: "#e3e6ea",
  },
  chipItemActive: {
    backgroundColor: ROJO_CLARO,
    borderColor: ROJO,
  },
  chipItemText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#50565d",
  },
  chipItemTextActive: {
    color: ROJO,
  },
});
