import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  pagina: {
    flex: 1,
    backgroundColor: "#f4f5f7",
  },
  contenidoPagina: {
    padding: 22,
  },
  encabezado: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 20,
  },
  titulo: {
    color: "#1f2329",
    fontSize: 29,
    fontWeight: "900",
  },
  subtitulo: {
    marginTop: 6,
    color: "#7b828a",
    fontSize: 14,
  },
  botonAgregar: {
    minHeight: 45,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 11,
    backgroundColor: "#b82018",
  },
  botonAgregarTexto: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "800",
  },
  botonPresionado: {
    opacity: 0.72,
  },
  resumen: {
    marginTop: 22,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 13,
  },
  tarjetaResumen: {
    minWidth: 205,
    flex: 1,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    borderWidth: 1,
    borderColor: "#e4e7ea",
    borderRadius: 13,
    backgroundColor: "#ffffff",
  },
  iconoResumen: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
    backgroundColor: "#eef0f2",
  },
  iconoActivo: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
    backgroundColor: "#ecfdf3",
  },
  iconoInactivo: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
    backgroundColor: "#fff0ef",
  },
  iconoAdvertencia: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
    backgroundColor: "#fff7ed",
  },
  valorResumen: {
    color: "#1f2329",
    fontSize: 22,
    fontWeight: "900",
  },
  etiquetaResumen: {
    marginTop: 3,
    color: "#7e858d",
    fontSize: 12,
    fontWeight: "600",
  },
  tarjetaTabla: {
    marginTop: 20,
    position: "relative",
    overflow: "visible",
    borderWidth: 1,
    borderColor: "#e3e6e9",
    borderRadius: 14,
    backgroundColor: "#ffffff",
  },
  barraHerramientas: {
    minHeight: 67,
    paddingHorizontal: 14,
    paddingVertical: 11,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#e8eaec",
    position: "relative",
    zIndex: 1000,
  },
  buscador: {
    width: "100%",
    maxWidth: 520,
    minHeight: 43,
    paddingHorizontal: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    borderWidth: 1,
    borderColor: "#dce0e4",
    borderRadius: 9,
    backgroundColor: "#fafbfc",
  },
  inputBusqueda: {
    flex: 1,
    color: "#1f2329",
    fontSize: 13,
    outlineStyle: "none",
  } as any,
  contenedorBotones: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    position: "relative",
    zIndex: 2000,
  },
  contenedorFiltro: {
    position: "relative",
    zIndex: 3000,
  },
  botonFiltrar: {
    minHeight: 42,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderWidth: 1,
    borderColor: "#dce0e4",
    borderRadius: 9,
    backgroundColor: "#ffffff",
  },
  botonFiltrarTexto: {
    color: "#1f2329",
    fontSize: 12,
    fontWeight: "700",
  },
  botonActualizar: {
    minHeight: 42,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderWidth: 1,
    borderColor: "#dce0e4",
    borderRadius: 9,
    backgroundColor: "#ffffff",
  },
  botonActualizarTexto: {
    color: "#1f2329",
    fontSize: 12,
    fontWeight: "700",
  },
  menuFiltros: {
    position: "absolute",
    top: 48,
    right: 0,
    width: 200,
    padding: 6,
    borderWidth: 1,
    borderColor: "#e2e5e9",
    borderRadius: 10,
    backgroundColor: "#ffffff",
    zIndex: 9999,
    elevation: 30,
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.12,
    shadowRadius: 10,
  },
  opcionFiltro: {
    minHeight: 40,
    paddingHorizontal: 11,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    borderRadius: 7,
  },
  opcionFiltroSeleccionada: {
    backgroundColor: "#eff6ff",
  },
  opcionPresionada: {
    opacity: 0.7,
  },
  opcionFiltroTexto: {
    color: "#68707a",
    fontSize: 13,
    fontWeight: "600",
  },
  opcionFiltroTextoSeleccionado: {
    color: "#2563eb",
    fontWeight: "700",
  },
  tabla: {
    width: "100%",
  },
  filaEncabezado: {
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f5f6f8",
  },
  fila: {
    minHeight: 74,
    flexDirection: "row",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "#eceef0",
    backgroundColor: "#ffffff",
  },
  celdaEncabezado: {
    paddingHorizontal: 8,
    color: "#5e6670",
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.2,
    flexShrink: 1,
  },
  celda: {
    paddingHorizontal: 8,
    color: "#4f565e",
    fontSize: 12,
    flexShrink: 1,
  },
  columnaId: {
    flex: 0.5,
  },
  columnaProducto: {
    flex: 2,
  },
  columnaDescripcion: {
    flex: 2,
  },
  columnaPrecio: {
    flex: 1,
  },
  columnaStock: {
    flex: 1.2,
  },
  columnaEstado: {
    flex: 1,
  },
  columnaAcciones: {
    flex: 1,
  },
  celdaProducto: {
    paddingHorizontal: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  imagenProductoContainer: {
    width: 48,
    height: 48,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#e3e6ea",
    backgroundColor: "#f7f8fa",
    alignItems: "center",
    justifyContent: "center",
  },
  imagenProducto: {
    width: "100%",
    height: "100%",
  },
  iconoProducto: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "#fff0ef",
  },
  nombreProducto: {
    flex: 1,
    color: "#24292f",
    fontSize: 13,
    fontWeight: "800",
  },
  precioTexto: {
    paddingHorizontal: 8,
    color: "#24292f",
    fontSize: 13,
    fontWeight: "800",
  },
  celdaStock: {
    paddingHorizontal: 8,
    justifyContent: "center",
    alignItems: "flex-start",
    gap: 4,
  },
  stockBadge: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 18,
  },
  stockNormal: {
    backgroundColor: "#ecfdf3",
  },
  stockBajo: {
    backgroundColor: "#fff7ed",
  },
  stockAgotado: {
    backgroundColor: "#fff0ef",
  },
  stockTexto: {
    fontSize: 12,
    fontWeight: "900",
  },
  stockNormalTexto: {
    color: "#15803d",
  },
  stockBajoTexto: {
    color: "#c2410c",
  },
  stockAgotadoTexto: {
    color: "#b82018",
  },
  textoDisponible: {
    color: "#838b94",
    fontSize: 10,
    fontWeight: "700",
  },
  textoIndisponible: {
    color: "#838b94",
    fontSize: 10,
    fontWeight: "700",
  },
  estadoBadge: {
    paddingHorizontal: 11,
    paddingVertical: 5,
    borderRadius: 18,
    alignSelf: "flex-start",
  },
  estadoActivoBadge: {
    backgroundColor: "#ecfdf3",
  },
  estadoInactivoBadge: {
    backgroundColor: "#fff0ef",
  },
  estadoActivoTexto: {
    color: "#15803d",
    fontSize: 11,
    fontWeight: "800",
  },
  estadoInactivoTexto: {
    color: "#b82018",
    fontSize: 11,
    fontWeight: "800",
  },
  acciones: {
    paddingHorizontal: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  botonAccion: {
    width: 33,
    height: 33,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#dbe0e5",
    borderRadius: 8,
    backgroundColor: "#ffffff",
  },
  botonEditar: {
    borderColor: "#bfdbfe",
    backgroundColor: "#eff6ff",
  },
  botonEliminar: {
    borderColor: "#fecaca",
    backgroundColor: "#fff1f2",
  },
  botonActivar: {
    borderColor: "#bbf7d0",
    backgroundColor: "#f0fdf4",
  },
  pieTabla: {
    padding: 14,
    borderTopWidth: 1,
    borderTopColor: "#eceef0",
    alignItems: "center",
  },
  pieTablaTexto: {
    color: "#7b828a",
    fontSize: 12,
    fontWeight: "600",
  },
  estadoCentro: {
    minHeight: 280,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  estadoTitulo: {
    marginTop: 14,
    color: "#282d33",
    fontSize: 17,
    fontWeight: "800",
  },
  estadoTexto: {
    marginTop: 6,
    color: "#7e868f",
    fontSize: 13,
  },
  cuerpoModal: {
    padding: 20,
  },
  grupoInput: {
    marginBottom: 14,
  },
  filaDosColumnas: {
    flexDirection: "row",
    gap: 12,
  },
  columnaMitad: {
    flex: 1,
  },
  label: {
    marginBottom: 6,
    color: "#525962",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  input: {
    minHeight: 44,
    paddingHorizontal: 13,
    borderWidth: 1,
    borderColor: "#d8dce1",
    borderRadius: 10,
    backgroundColor: "#ffffff",
    color: "#1f2329",
    fontSize: 13,
  },
  inputError: {
    borderColor: "#b82018",
    backgroundColor: "#fffafa",
  },
  inputTextArea: {
    minHeight: 70,
    paddingTop: 10,
    paddingBottom: 10,
    textAlignVertical: "top",
  },
  errorCampo: {
    marginTop: 4,
    color: "#b82018",
    fontSize: 11,
    fontWeight: "700",
  },

  // ==========================================
  // ESTILOS DE SUBIDA Y EDICIÓN DE IMAGEN
  // ==========================================
  seccionImagen: {
    marginBottom: 18,
  },
  dropzoneSubida: {
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: "#d5dbe2",
    borderRadius: 16,
    padding: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fafbfc",
  },
  iconoSubidaCaja: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#fff0ef",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  tituloSubida: {
    fontSize: 14,
    fontWeight: "800",
    color: "#20252b",
    textAlign: "center",
  },
  subtituloSubida: {
    fontSize: 11,
    color: "#7b828a",
    marginTop: 3,
    textAlign: "center",
  },
  botonExaminar: {
    marginTop: 12,
    backgroundColor: "#b82018",
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  botonExaminarTexto: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "800",
  },
  previewCard: {
    borderWidth: 1,
    borderColor: "#e3e6ea",
    borderRadius: 16,
    padding: 14,
    backgroundColor: "#f8f9fb",
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  previewImagenGrande: {
    width: 80,
    height: 80,
    borderRadius: 12,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#eceef1",
  },
  previewInfo: {
    flex: 1,
  },
  previewBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: "#ecfdf3",
    marginBottom: 6,
  },
  previewBadgeTexto: {
    fontSize: 10,
    fontWeight: "800",
    color: "#15803d",
  },
  previewAcciones: {
    flexDirection: "row",
    gap: 8,
    marginTop: 6,
  },
  botonCambiarFoto: {
    backgroundColor: "#eff6ff",
    borderWidth: 1,
    borderColor: "#bfdbfe",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  botonCambiarFotoTexto: {
    color: "#1d4ed8",
    fontSize: 11,
    fontWeight: "800",
  },
  botonEliminarFoto: {
    backgroundColor: "#fff1f2",
    borderWidth: 1,
    borderColor: "#fecaca",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  botonEliminarFotoTexto: {
    color: "#b82018",
    fontSize: 11,
    fontWeight: "800",
  },
});